project_id = "ooslnjewdrobciiucmwe"

[functions.generate-palettes]
verify_jwt = false

[functions.upload-imgbb]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = false

[functions.shorten-link]
verify_jwt = false
