import { useCallback, useEffect, useState } from "react";
import { Helmet } from "react-helmet-async";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { useRealtimeTables } from "@/hooks/useRealtimeTables";
import { Link } from "react-router-dom";
import { Save, Trash2, RotateCcw, LogOut } from "lucide-react";

type Segment = {label:string;value:number;weight:number};
type Settings = {is_open:boolean;signups_open:boolean;wheel_open:boolean;welcome_coins:number;spin_cost:number;wheel_segments:Segment[]};
type Player = {id:string;name:string;coins:number;blocked:boolean};
const Panel = ({title,children}: {title:string;children:React.ReactNode}) => <section className="zgames-glass rounded-lg p-5"><h2 className="mb-4 text-lg font-semibold">{title}</h2>{children}</section>;
export default function AdminDaily() {
 const [auth,setAuth]=useState(false), [email,setEmail]=useState(""), [password,setPassword]=useState(""), [busy,setBusy]=useState(false), [message,setMessage]=useState("");
 const [settings,setSettings]=useState<Settings|null>(null), [players,setPlayers]=useState<Player[]>([]), [checks,setChecks]=useState<{player_id:string;day:string;coins:number}[]>([]), [spins,setSpins]=useState<{player_id:string;value:number;created_at:string}[]>([]);
 const [draft,setDraft]=useState<Settings|null>(null);
 const sync=useCallback(async()=>{ const [s,report]=await Promise.all([supabase.from("daily_settings").select("*").eq("id",1).maybeSingle(),supabase.rpc("daily_admin_report")]); if(s.data) {setSettings(s.data as unknown as Settings);setDraft(prev=>prev??(s.data as unknown as Settings));} if(report.data) {const data=report.data as unknown as {players:Player[];checkins:{player_id:string;day:string;coins:number}[];spins:{player_id:string;value:number;created_at:string}[]};setPlayers(data.players);setChecks(data.checkins);setSpins(data.spins);} },[]);
 useEffect(()=>{let active=true; void supabase.auth.getUser().then(async ({data})=>{if(!active)return;if(data.user){const {data:allowed}=await supabase.rpc("daily_is_admin"); if(active)setAuth(Boolean(allowed));}}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{if(!session) {setAuth(false);setSettings(null);setDraft(null);} }); return ()=>{active=false;subscription.unsubscribe();};},[]);
 useRealtimeTables({channelName:"daily-admin",tables:["daily_settings","daily_players","daily_checkins","daily_spins"],enabled:auth,fallbackMs:7000,onSync:sync});
 const run=async(action:string,payload:Record<string,unknown>={})=>{setBusy(true);const {error}=await supabase.rpc("daily_admin",{p_action:action,p_payload:payload});setBusy(false);setMessage(error?`Não foi possível salvar: ${error.message}`:"Alterações salvas.");if(!error){setDraft(null);void sync();}return !error;};
 const login=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);const {error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);setPassword("");if(error){setMessage("Não foi possível entrar. Confira e-mail e senha.");return;} const {data}=await supabase.rpc("daily_is_admin");setAuth(Boolean(data));setMessage(data?"":"Esta conta não tem acesso ao painel.");};
 const logout=async()=>{await supabase.auth.signOut();setAuth(false);setDraft(null);};
 return <main className="zgames-page min-h-screen px-4 py-8 text-foreground"><Helmet><title>Administração do Vibe Check-in | LabXat</title><meta name="description" content="Painel de controle do Vibe Check-in." /></Helmet><div className="mx-auto max-w-6xl"><header className="mb-7 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-secondary">RÁDIO ALTA VIBE</p><h1 className="text-3xl font-bold">Painel · Vibe Check-in</h1></div><div className="flex gap-2"><Button variant="glass" asChild><Link to="/daily">Ver jogo</Link></Button>{auth&&<Button variant="ghost" onClick={logout}><LogOut/>Sair</Button>}</div></header>
 {!auth ? <Panel title="Acesso administrativo"><form onSubmit={login} className="max-w-sm space-y-3"><Input aria-label="E-mail" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-mail" required/><Input aria-label="Senha" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Senha" required/><Button type="submit" disabled={busy} className="w-full">Entrar</Button></form><p className="mt-3 text-sm text-muted-foreground">Acesso restrito a administradores autorizados.</p></Panel> : <div className="grid gap-5 lg:grid-cols-2"><Panel title="Controles do jogo"><div className="space-y-4">{([["is_open","Jogo aberto"],["signups_open","Novos cadastros"],["wheel_open","Roleta aberta"]] as const).map(([key,label])=><label key={key} className="flex items-center justify-between gap-4 border-b border-border pb-3">{label}<Switch checked={Boolean(draft?.[key])} onCheckedChange={value=>setDraft(d=>d?{...d,[key]:value}:d)}/></label>)}{([["welcome_coins","VibeCoins de boas-vindas"],["spin_cost","Custo de cada giro"]] as const).map(([key,label])=><label key={key} className="block text-sm">{label}<Input type="number" min={0} max={10000} value={draft?.[key]??0} onChange={e=>setDraft(d=>d?{...d,[key]:Number(e.target.value)}:d)} className="mt-1"/></label>)}<Button disabled={busy||!draft} onClick={()=>draft&&void run("settings",{is_open:draft.is_open,signups_open:draft.signups_open,wheel_open:draft.wheel_open,welcome_coins:draft.welcome_coins,spin_cost:draft.spin_cost,wheel_segments:draft.wheel_segments})}><Save/> Salvar configurações</Button></div></Panel>
 <Panel title="Roleta · fatias e chances"><p className="mb-3 text-sm text-muted-foreground">O check-in sempre vale o número do dia; estes valores afetam apenas a roleta.</p><div className="space-y-3">{draft?.wheel_segments.map((segment,i)=><div key={i} className="grid grid-cols-[32px_1fr_1fr_1fr] items-center gap-2 text-sm"><span>{i+1}</span><Input aria-label={`Nome da fatia ${i+1}`} value={segment.label} maxLength={20} onChange={e=>setDraft(d=>d?{...d,wheel_segments:d.wheel_segments.map((s,n)=>n===i?{...s,label:e.target.value}:s)}:d)}/><Input aria-label={`Valor da fatia ${i+1}`} type="number" min={-1} max={10000} value={segment.value} onChange={e=>setDraft(d=>d?{...d,wheel_segments:d.wheel_segments.map((s,n)=>n===i?{...s,value:Number(e.target.value)}:s)}:d)}/><Input aria-label={`Peso da fatia ${i+1}`} type="number" min={0} max={100} value={segment.weight} onChange={e=>setDraft(d=>d?{...d,wheel_segments:d.wheel_segments.map((s,n)=>n===i?{...s,weight:Number(e.target.value)}:s)}:d)}/></div>)}<p className="text-xs text-muted-foreground">Colunas: nome, valor e peso. Valor −1 devolve o custo do giro.</p><Button disabled={busy||!draft} onClick={()=>draft&&void run("settings",{wheel_segments:draft.wheel_segments})}><Save/> Salvar roleta</Button></div></Panel>
 <Panel title={`Jogadores · ${players.length}`}><div className="max-h-[520px] space-y-2 overflow-auto">{players.map(p=><div key={p.id} className="flex flex-wrap items-center gap-2 border-b border-border py-2"><strong className="min-w-24 flex-1">{p.name}</strong><Input aria-label={`Saldo de ${p.name}`} type="number" min={0} className="w-28" value={p.coins} onChange={e=>setPlayers(list=>list.map(x=>x.id===p.id?{...x,coins:Number(e.target.value)}:x))}/><Button size="icon" variant="glass" title="Salvar saldo" aria-label={`Salvar saldo de ${p.name}`} onClick={()=>void run("adjust",{id:p.id,coins:p.coins})}><Save/></Button><Button size="sm" variant={p.blocked?"secondary":"glass"} onClick={()=>void run("adjust",{id:p.id,blocked:!p.blocked})}>{p.blocked?"Desbloquear":"Bloquear"}</Button><Button size="icon" variant="destructive" aria-label={`Excluir ${p.name}`} title="Excluir jogador" onClick={()=>{if(confirm(`Excluir ${p.name} e todo o histórico?`))void run("remove",{id:p.id});}}><Trash2/></Button></div>)}</div></Panel>
 <Panel title="Relatório"><p className="mb-3 text-sm text-muted-foreground">{checks.length} check-ins recentes · {spins.length} giros recentes</p><div className="max-h-[420px] overflow-auto text-sm"><h3 className="font-semibold">Check-ins</h3>{checks.map((c,i)=><div key={i} className="flex justify-between border-b border-border py-2"><span>{players.find(p=>p.id===c.player_id)?.name??"Jogador removido"} · {c.day}</span><span>+{c.coins}</span></div>)}<h3 className="mt-5 font-semibold">Giros</h3>{spins.map((s,i)=><div key={i} className="flex justify-between border-b border-border py-2"><span>{players.find(p=>p.id===s.player_id)?.name??"Jogador removido"} · {new Date(s.created_at).toLocaleString("pt-BR")}</span><span>{s.value===-1?"Devolvido":s.value}</span></div>)}</div></Panel>
 <Panel title="Reiniciar temporada"><p className="mb-4 text-sm text-muted-foreground">Apaga check-ins, giros e sessões; zera os saldos dos jogadores. Não pode ser desfeito.</p><Button variant="destructive" disabled={busy} onClick={()=>{if(confirm("Resetar toda a temporada e zerar os saldos?"))void run("reset",{confirm:"RESETAR"});}}><RotateCcw/> Resetar temporada</Button></Panel></div>}{message&&<p role="status" className="mt-5 text-sm text-secondary">{message}</p>}</div></main>;
}
